function G_J2 = computeJ2GravityGradient_generated(in1,mu,J2,R_ref)
%computeJ2GravityGradient_generated
%    G_J2 = computeJ2GravityGradient_generated(IN1,MU,J2,R_ref)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    17-Sep-2025 19:25:57

x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = R_ref.^2;
t3 = x.^2;
t5 = y.^2;
t7 = z.^2;
t4 = t3.^2;
t6 = t5.^2;
t8 = t7.^2;
t9 = t3.*3.0;
t10 = t5.*3.0;
t11 = t7.*4.0;
t12 = t7.*6.0;
t17 = t3+t5+t7;
t13 = t8.*4.0;
t14 = -t11;
t15 = -t12;
t16 = t5.*t9;
t19 = 1.0./t17.^(9.0./2.0);
t18 = t3+t5+t15;
t20 = t9+t10+t14;
t21 = J2.*mu.*t2.*t18.*t19.*x.*y.*(1.5e+1./2.0);
t22 = J2.*mu.*t2.*t19.*t20.*x.*z.*(1.5e+1./2.0);
t23 = J2.*mu.*t2.*t19.*t20.*y.*z.*(1.5e+1./2.0);
G_J2 = reshape([J2.*mu.*t2.*t19.*(t4.*4.0-t6+t13+t16-t3.*t7.*2.7e+1+t7.*t10).*(3.0./2.0),t21,t22,t21,J2.*mu.*t2.*t19.*(-t4+t6.*4.0+t13+t16-t5.*t7.*2.7e+1+t7.*t9).*(3.0./2.0),t23,t22,t23,J2.*mu.*t2.*t19.*(t4.*3.0+t6.*3.0+t8.*8.0+t3.*t5.*6.0-t3.*t7.*2.4e+1-t5.*t7.*2.4e+1).*(-3.0./2.0)],[3,3]);
end
