clear all; close all; clc; format short g; warning off;
%% TESTCASE 2. PARTIAL COT Equinox Case
%--------------------------------------------------------------------------
% Here we search for a sequence of 10 consecutive fly-bys in Enceladus.
% This is similar to those proposed in the L4 report.
%% 1. Loading Constants & parameters
%--------------------------------------------------------------------------
% Upload database generated by Saturn_Enceladus Search
load('Saturn_Enceladus_Titan_exploration_results_full4e.mat')
% --------------------------------------------------------------------------
% Constants & Parameters
RAD=pi/180;
Days2Sec=3600*24;
nEnceladus=sqrt(pars.Planet.mu/pars.Moon.OrbRad(1)^3);
nTitan=sqrt(pars.Planet.mu/pars.Moon.OrbRad(2)^3);
%--------------------------------------------------------------------------
% Define Central Body & Moon of interest
parsPLOT.INPUTS.idCentral  = 6; % (5 = Jupiter; 6 = Saturn; 7 = Uranus)
parsPLOT.INPUTS.idMoon     = 1; % (1 = Io; 2 = Europa; 3 = Ganymede; 4 = Callisto)
%(1 = Enceladus; 2 = Thetys; 3 = Dione; 4 = Rhea; 5 = Titan)
%(1 = Miranda; 2 = Ariel; 3 = Umbriel; 4 = Titania; 5 = Oberon)

[parsPLOT.Planet.mu, parsPLOT.Planet.EquRad, parsPLOT.Planet.OrbRad, parsPLOT.Planet.hmin] = planetConstants(parsPLOT.INPUTS.idCentral); %[km3/s2],[km],[km] & [km]

%Retrieve Desired Moon Parameters
if parsPLOT.INPUTS.idCentral == 3
    parsPLOT.Moon.OrbRad = 384748; parsPLOT.Moon.mu  = getAstroConstants('Moon','mu'); %[km],[km3/s2]
    parsPLOT.Moon.EquRad = getAstroConstants('Moon','Radius'); parsPLOT.Moon.hmin = 50;  %[km], [km]
elseif parsPLOT.INPUTS.idCentral == 5
    [parsPLOT.Moon.OrbRad, parsPLOT.Moon.mu, parsPLOT.Moon.EquRad, parsPLOT.Moon.hmin] = jupMoonsConstants(parsPLOT.INPUTS.idMoon); %[km],[km3/s2],[km] & [km]
elseif pars.INPUTS.idCentral == 6
    [parsPLOT.Moon.OrbRad, parsPLOT.Moon.mu, parsPLOT.Moon.EquRad, parsPLOT.Moon.hmin] = satMoonsConstants(parsPLOT.INPUTS.idMoon); %[km],[km3/s2],[km] & [km]
else
    [parsPLOT.Moon.OrbRad, parsPLOT.Moon.mu, parsPLOT.Moon.EquRad, parsPLOT.Moon.hmin] = uranusMoonsConstants(pars.INPUTS.idMoon); %[km],[km3/s2],[km] & [km]
end

for i = 1:size(parsPLOT.INPUTS.idMoon,2)
    parsPLOT.Moon.Vel(i)    = sqrt(parsPLOT.Planet.mu/parsPLOT.Moon.OrbRad(i));           %[km/s] Moon Orbital velocity
    parsPLOT.Moon.Period(i) = 2*pi*sqrt(parsPLOT.Moon.OrbRad(i)^3/parsPLOT.Planet.mu);    %[s] Moon orbital period
    parsPLOT.Moon.HillSph(i) = parsPLOT.Moon.OrbRad(i)*( parsPLOT.Moon.mu(i)/(3*(parsPLOT.Moon.mu(i) + parsPLOT.Planet.mu)))^(1/3);     %[km] Moon Hill's Sphere
end

%--------------------------------------------------------------------------
%Load some necessary parameters
%Define parameters regarding the flyby
parsPLOT.INPUTS.Flyby.min_h    = 25;   %[km] Minimum flyby altitude
parsPLOT.GroundTr.npoints      = 30e3; % N° of time steps for ground-track propagation
parsPLOT.GroundTr.t_prop       = 10;    %[minutes] Time of flyby hyperbola propagation
parsPLOT.INPUTS.Flyby.hMapping = 1500;  %[km] Max altitude to consider mapping

%Define starting epoch
parsPLOT.INPUTS.epoch0 = 0;
%Load sectirs for groundtrack plots
load('sectorObj.mat');
load('sectorObj_.mat');
parsPLOT.sectorObj  = sectorObj;
parsPLOT.sectorObj_ = sectorObj_;
parsPLOT.rect       = defineRectangleMapping(); % --> save the rectangle mapping
% --------------------------------------------------------------------------
% Epremeris Moons Set up
KepTitan=[pars.Moon.OrbRad(2) 0 0 0 0 0];
KepEnceladus=[pars.Moon.OrbRad(1) 0 0 0 0 0];
SVTitan_func = @(TrA)kep2car([KepTitan(1:5) TrA],pars.Planet.mu);
SVEnceladus_func = @(TrA)kep2car([KepEnceladus(1:5) TrA],pars.Planet.mu);
% --------------------------------------------------------------------------
%%
Delta_V=zeros(1,length(treeExploration));
Score_TidalSpread=zeros(1,length(treeExploration));
Score_TidalSpread2=zeros(1,length(treeExploration));
Score_ScientificInteres=zeros(1,length(treeExploration));
Delta_longitude=zeros(1,length(treeExploration));
Total_time_of_flight=zeros(1,length(treeExploration));

for iN=1:length(treeExploration)
    % Analyse each individual route
    Entire_route=treeExploration{iN}.route;

    % Enceladus FlyBys
    indexRelevantFlyBys=find(Entire_route(:,8)==1);
    numEnceladusFB(iN)=length(indexRelevantFlyBys);
    % Enhance TreeExploration Structure
    treeExploration{iN}.numEnceladusFB=numEnceladusFB(iN);

    Delta_V(iN)=treeExploration{iN}.TotalDVCost;

    % Diversity on Flybys
    RelevantNodes=[Entire_route(indexRelevantFlyBys,9) Entire_route(indexRelevantFlyBys,10) Entire_route(indexRelevantFlyBys,11)/RAD];
    Unique_nodes = table(round(RelevantNodes(:,1)/0.500),RelevantNodes(:,2),round(RelevantNodes(:,3)/90));
    Score_ScientificInteres(iN)=height(unique(Unique_nodes));


    % True Longitude of FlyBys
    LongitudeofallEnceladusNodes=Entire_route(indexRelevantFlyBys,13);
    Unique_nodes = table(round(LongitudeofallEnceladusNodes/RAD/15));
    Score_TidalSpread(iN)=height(unique(Unique_nodes));

    % Longitude of furthest Enceladus FBs - relevant to illumination
    % Conditions
    Initial_Longitude=Entire_route(indexRelevantFlyBys(1),13);
    LongitudeofallEnceladusNodes=Entire_route(indexRelevantFlyBys,13);
    Delta_longitude(iN)=max(abs((Initial_Longitude-LongitudeofallEnceladusNodes)))/RAD;

    Travel_matrix=zeros(length(LongitudeofallEnceladusNodes));
    for itm=1:length(LongitudeofallEnceladusNodes)
        for jtm=itm:length(LongitudeofallEnceladusNodes)
            Travel_matrix(itm,jtm)=abs(LongitudeofallEnceladusNodes(itm)-LongitudeofallEnceladusNodes(jtm));
        end
    end
    Score_TidalSpread2(iN)=height(unique(Unique_nodes))*sum(Travel_matrix(:));



    %Overall Time of Flight
    Total_time_of_flight(iN)=sum(Entire_route(:,7)); % days
    %--------------------------------------------------------------------------
    % Enhance TreeExploration Structure
    treeExploration{iN}.Score_ScientificInteres= Score_ScientificInteres(iN);
    treeExploration{iN}.Delta_longitude_excursion=Delta_longitude(iN);
    treeExploration{iN}.TotalTimeofFlight=Total_time_of_flight;
end

% Create figure
figure1 = figure;
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
% Create plot
plot(Delta_longitude,Delta_V,'MarkerFaceColor',[0 0 0],'Marker','o','LineStyle','none');
% Create ylabel
ylabel('\Deltav [km/s]');
% Create xlabel
xlabel('\DeltaL [degrees]');
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',12,'FontWeight','bold',...
    'XGrid','on','YGrid','on');
